#!/usr/bin/bash

# my cobbler steps (all as sudo) on fresh Fedora 41 server, generally [following this howto](https://cobbler.readthedocs.io/en/latest/quickstart-guide.html):

SVR=$1

YUM=yum
#YUM=dnf

if [ -z "${SVR}" ]; then
	echo "Usage: ./cobbler-install SERVER_IP_ADDRESS"
	exit
fi

cd /tmp

# disable selinux
# TODO: fix selinux setup
setenforce permissive

# disable selinux on next boot too
# TODO: fix selinux setup
sed -i 's/^SELINUX=.*/SELINUX=permissive/' /etc/selinux/config

# Rocky9
${YUM} install -y epel-release
/usr/bin/crb enable
${YUM} module enable cobbler

# install packages needed and/or useful for cobbler
${YUM} install -y tar patch wget httpd tftp-server syslinux debmirror dnf-utils grub2-efi-x64 grub2-tools-efi grub2-efi-x64-modules python3-hivex

# install cobbler
${YUM} install -y cobbler
# on FC41 needed to apply cobbler fix from [here](https://bugzilla.redhat.com/show_bug.cgi?id=2335620)
#dnf upgrade -y --enablerepo=updates-testing --refresh --advisory=FEDORA-2025-c31f65751c
# maybe combine the install and upgrade...
#dnf install -y --enablerepo=updates-testing --refresh --advisory=FEDORA-2025-c31f65751c cobbler

# prepare debian mirror
sed -i -e 's/^# @di_dists/$di_dists/' -e 's/^# @di_archs/$di_archs/' -e 's/@dists="sid"/$dists="bookworm"/' -e 's/@arches="i386"/$arches="x86_64"/' /etc/debmirror.conf

# adjust some network settings
sed -i "s/^server:.*/server: ${SVR}/" /etc/cobbler/settings
sed -i "s/^server:.*/server: ${SVR}/" /etc/cobbler/settings.yaml

# adjust some network settings (only if doing DHCP on this machine)
sed -i "s/^next_server:.*/next_server: ${SVR}/" /etc/cobbler/settings
sed -i "s/^next_server:.*/next_server: ${SVR}/" /etc/cobbler/settings.yaml
sed -i "s/^next_server_v4:.*/next_server_v4: ${SVR}/" /etc/cobbler/settings
sed -i "s/^next_server_v4:.*/next_server_v4: ${SVR}/" /etc/cobbler/settings.yaml

# patch old cobbler to get the right signatures (thanks Purna!)
if [ -a /etc/cobbler/settings ]; then
	test=$(grep -c ^signature_url: /etc/cobbler/settings)
	if [ $test = "0" ]; then
		#echo "signature_url: https://cobbler.github.io/signatures/3.0.x/latest.json" >> /etc/cobbler/settings
		wget https://cobbler.github.io/signatures/2.8.x/latest.json
		patch -p0 < bookworm-patch-cobbler-2.8.latest.json.diff
		cp latest.json /var/www/html
		echo "signature_url: http://localhost/latest.json" >> /etc/cobbler/settings
	fi
fi

# stop, enable and start TFTP
systemctl stop tftp.socket
systemctl stop tftp.service
systemctl enable tftp
systemctl start tftp

# stop, enable and start HTTPD
systemctl stop httpd.service
systemctl enable httpd
systemctl start httpd

# stop, enable and start RSYNCD
systemctl stop rsyncd.service
systemctl enable rsyncd
systemctl start rsyncd

# wait for the file, webservers and rsync services to start
sleep 10

# stop, enable and start cobblerd
systemctl stop cobblerd.service
systemctl enable cobblerd
systemctl start cobblerd

# cobbler takes several seconds to start
sleep 10

# update signatures (should grab the bookworm signature)
cobbler signature update

# generate bootloaders eg. /var/lib/tftpboot/pxelinux.0
# FC41
cobbler mkloaders
# SNG7
sh ~/mkloaders.sh

# open the firewall for TFTP
firewall-cmd --add-service=tftp --perm

# open the firewall for HTTP
firewall-cmd --add-service=http --perm

# restart the firewall
firewall-cmd --reload

# check (optional)
cobbler check

